# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
## For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: testrunner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_ENV: development
  USERS_SERVICE_URL: http://users-service:3000
  MOVIES_SERVICE_URL: http://movies-service:3000
  OMDB_API_KEY: a69b8c8f



jobs:
  build:
    runs-on: self-hosted
    steps:

    - name: Checkout
      uses: actions/checkout@v2

#     - name: Create network 
#       run: sudo docker network create gcloud_example_pipeline

    - name: Create network
      run: sudo docker network create --driver bridge gcloud_example_pipeline || true

    - name: check docker running containers 
      run: sudo docker ps

    - name: Build App containers 
      run: sudo docker-compose build

    #- name: Run containers 
    #  run: sudo docker-compose up -d

    #- name: Docker refresh containers
    #  run: sudo docker restart $(sudo docker ps -q)
